name: CI

on:
  push:
    branches:
      - advance-online-app
  pull_request:
    branches:
      - advance-online-app

jobs:
  build_and_deploy_distribute:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: API GPT
        run: echo ${{secrets.API_GPT}} | base64 -d > lib/app/constants/api_constant.dart

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.UPLOAD_KEYSTORE }}
    
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build
        run: flutter build apk --flavor production -t lib/main_production.dart

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ourtutor-tester
          releaseNotes: "${{ github.event.pull_request_review_comment.comment.body }}"
          file: build\app\outputs\flutter-apk\app-production-release.apk
